#!/bin/bash

VIDEO_INPUT_FILE=$1

VIDEO_OUTPUT_EXTENSION=".mp4"
VIDEO_OUTPUT_FILE="$VIDEO_INPUT_FILE$VIDEO_OUTPUT_EXTENSION"

ffmpeg -i $VIDEO_INPUT_FILE -c copy -strict -2 -map 0:0 -map 0:1 $VIDEO_OUTPUT_FILE
